config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/my_colleges', to: 'static_pages#my_colleges'
  get '/most_reviews', to: 'static_pages#most_reviews'
  get '/college_rankings', to: 'static_pages#college_rankings'
  get '/signup', to: 'users#new'
  get '/show_all_colleges', to: 'colleges#show_all_colleges'
  get '/login',   to: 'sessions#new'
  get '/submit_review', to: 'reviews#new'
  get '/submit_ranking', to: 'rankings#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :colleges
  resources :reviews do
    collection do
      get :verify
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @reviews = Review.order('college_name ASC').paginate(:page => params[:page], :per_page => 15)
  end
  
  def most_reviews
    @colleges = College.order(reviews_count: :desc).paginate(page: params[:page], per_page: 15, :total_entries => 45)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<html>
	<head>
    <title>PunaLink</title>
		<link rel="stylesheet" href="custom.scss">
	<head>

	<body class="body">
		<div class="container-small container">
			<div class="row" style="margin-bottom: 50px">
				<div id="welcome" class="col-md-12">
					<div class="short row">
						<label id="header"><u>Welcome to PunaLink,</u></label>
						<p class="welcome-p-1">A resource for Punahou Academy students sourced from Punahou Alumni. Get real input from our alumni on their colleges.  Find out what other Oahuans think about everything from campus life, to academic rigor, to food.  The real inside info, by Punahou, for Punahou</p>
					</div>
				</div>
			</div>
			
			<!-- Paginate Reviews-->
			<div class="row">
				<div style="display: block; margin: 0 auto; text-align: center">
					<label id="header"><u>All Reviews: </u></label>
				</div>
				
				<div class="col-md-12">
					<div id="results" class="row">
						<table class="table black-border col-md-12" style="margin-top: 20px; margin-left: 2.2%; width: 96%">
							<thead style="background: #D6E4FF">
								<% if current_user == nil || current_user.admin == false %>
									<tr>
										<th style="width: 20%">Review Author</th>
										<th style="width: 30%">Review School Name</th>
										<th>Link</th>
									</tr>
								<% else %>
									<tr>
										<th style="width: 20%">Review Author</th>
										<th style="width: 30%">Review School Name</th>
										<th>Link</th>
										<th>Verified?</th>
										<td>Delete?</td>
									</tr>
								<% end %>
							</thead>
							<tbody>
								<% if current_user == nil || current_user.admin == false %>
									<%= will_paginate @reviews %>
									<% @reviews.each do |r| %>
										<% if r.verified == true %>
		                                    <tr>
		                                        <td><%= r.name %></td>
		                                        <td><%= r.college_name %></td>
		                                        <td><%= link_to "Go to review of " + r.college_name, r %></td>
		                                    </tr>
	                                    <% end %>
	                                <% end %>
	                            <% else %>
	                            	<%= will_paginate @reviews %>
	                            	<% @reviews.each do |r| %>
										<% if r.verified == false %>
		                                    <tr>
		                                        <td><%= r.name %></td>
		                                        <td><%= r.college_name %></td>
		                                        <td><%= link_to "Go to review of " + r.college_name, r %></td>
		                                        <td><%= link_to "Verify", verify_reviews_path(:id => r.id) %></td>
		                                        <td><%= button_to "Delete", r, method: :delete, data: { confirm: 'Are you sure you want to delete this review?' }, :class => "btn btn-danger" %></td>
		                                    </tr>
		                                <% else %>
		                                	<tr>
		                                        <td><%= r.name %></td>
		                                        <td><%= r.college_name %></td>
		                                        <td><%= link_to "Go to review of " + r.college_name, r %></td>
		                                        <td>Verified</td>
		                                        <td><%= button_to "Delete", r, method: :delete, data: { confirm: 'Are you sure you want to delete this review?' }, :class => "btn btn-danger" %></td>
		                                    </tr>
	                                    <% end %>
	                                <% end %>
                                <% end %>
							</tbody>
						</table>
					</div>
				</div>
			</div> <!-- row -->
			
			<!-- The extra "row" div ensures that the following <p> is placed on a separate line-->
			<div class="row">
				<p class="welcome-p-1">Click on the 'Colleges' tab to search for reviews of a specific college</p>
			</div>
		</div>
	</body>
</html>

app/views/static_pages/most_reviews.html.erb
<!doctype html>

<html>
	<head>
		<link rel="stylesheet" href="custom.scss">
		<title>Most Reviews</title>
	<head>

	<body class="body">
		<div class="container-small container" style="background-color: white">
			<div class="row">
				<%= will_paginate @colleges %>
				<table class="black-border table" style="margin-top: 0">
					<thead style="background: #D6E4FF">
						<tr>
							<th style="width: 40%">School Name</th>
							<th># Reviews</th>
						</tr>
					</thead>
					<tbody>
						<% @colleges.each do |college| %>
  							<tr>
								<td><%= link_to college.name,   college %></td>
								<td><%= college.reviews_count %></td>
  							</tr>
						<% end %>
						</tr>
					</tbody>
				</table>
			</div> <!-- row -->
		</div>
	</body>


</html>