config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/my_colleges', to: 'static_pages#my_colleges'
  get '/most_reviews', to: 'static_pages#most_reviews'
  get '/college_rankings', to: 'static_pages#college_rankings'
  get '/signup', to: 'users#new'
  get '/show_all_colleges', to: 'colleges#show_all_colleges'
  get '/login',   to: 'sessions#new'
  get '/submit_review', to: 'reviews#new'
  get '/submit_ranking', to: 'rankings#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :colleges
  resources :reviews do
    collection do
      get :verify
    end
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" id="punahou-nav">
  <div class="punahou-image container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li id="nav-text"><%= link_to "Home",   root_path %></li>
        <li id="nav-text"><%= link_to "Colleges",   colleges_path %></li>
        <li id="nav-text"><%= link_to "Most Reviews",   most_reviews_path %></li>
        <li id="nav-text"><%= link_to "Submit a Review",   submit_review_path %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li id="nav-text"><%= link_to "Log out", logout_path, method: "delete"%></li>
        <% else %>
            <li id="nav-text"><%= link_to "Login",   login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  
  <link rel="shortcut icon" type="image/x-icon" href="https://img.clipartfest.com/5e6a661902e5bcd776bb39ecc3310c8e_light-yellow-circle-clip-art-yellow-circle-clipart_300-300.png" />
  
  <%= render 'layouts/nav' %>
</head>
<body>
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
  <%= yield %>
</body>
</html>